services:
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - kong
    networks:
      - kong-net
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always

  kong:
    image: kong:latest
    container_name: kong
    restart: always
    environment:
      KONG_DATABASE: "off"
      KONG_PROXY_LISTEN: "0.0.0.0:8000"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_DECLARATIVE_CONFIG: "/etc/kong/kong.yml"
    networks:
      - kong-net
    volumes:
      - ./kong.yml:/etc/kong/kong.yml  
    ports:
      - "8000:8000" 
      - "8001:8001"

networks:
  kong-net:
    driver: bridge
